### ISSUE TITLE
Indentation depth configurable using something else than tab-width 

### ISSUE THREAD

**Issue by jscheid** [defunkt/coffee-mode#16]
Hi,

it's quite unusual for an Emacs major mode to use tab-width for indentation depth. c-mode, c++-mode, javascript-mode etc use c-basic-offset; python-mode uses py-indent-offset; ruby-mode uses ruby-indent-level; sh-mode uses sh-basic-offset... you get the idea. See also http://www.emacswiki.org/emacs/IndentationBasics

It would be nice if coffee-mode would have a similar setting.  I prefer to leave tab-width at 8 for best compatibility with other people's code, but that's far too wide for indentation of course.

Thanks!

PS: It looks like sometimes tab-width is used (implicitly by indent.el's insert-tab), sometimes coffee-tab-width. Is this by design?

**Comment by To1ne** [comment]
With the existence of `coffee-tab-width` this is not a big issue anymore. This variable allows you to set `coffee-tab-width` without touching `tab-width`.
But in fact the variable name is not really correct, because the documentation of `tab-width` shows:

```
tab-width is a variable defined in `C source code'.
Its value is 8

  Automatically becomes buffer-local when set.
  This variable is safe as a file local variable if its value
  satisfies the predicate `integerp'.

Documentation:
Distance between tab stops (for display of tab characters), in columns.
NOTE: This controls the display width of a TAB character, and not
the size of an indentation step.
This should be an integer greater than zero.

You can customize this variable.
```

**Comment by syohex** [comment]
> I suggest renaming coffee-tab-width to something like coffee-indent-width and make its default value use standard-indent.

It is difficult to rename and change default value for backward compatibility.
