### ISSUE TITLE
error when loading coffee-mode on ubuntu 14.04

### ISSUE THREAD

**Issue by donhill** [defunkt/coffee-mode#243]
I am getting a strange load error on ubuntu 14.04 when loading coffee-mode. I am using GNU Emacs 24.3.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23). Here is first part of the stack. My config works fine on OSX.

Any thoughts?

Debugger entered--Lisp error: (invalid-function "coffeescript")
  "coffeescript"("major" "mode")
  byte-code("\300\301\302\303\304\305\306\307\310\311\312\"&\207" [define-package "coffee-mode" "20140524.2002" "Major mode to edit CoffeeScript files in Emacs" ((emacs "24.1") (cl-lib "0.5")) :url "http://github.com/defunkt/coffee-mode" :keywords "coffeescript" "major" "mode"] 11)
  load("/home/dhill/.emacs.d/elpa/coffee-mode-20140524.2002/coffee-mode-pkg" nil t)
  package-load-descriptor("~/.emacs.d/elpa" "coffee-mode-20140524.2002")

**Comment by syohex** [comment]
Please reopen if you still have this problem.
