### ISSUE TITLE
Indenting when entire buffer is active should properly indent the buffer rather than inserting two spaces on every line

### ISSUE THREAD

**Issue by brianmingus** [defunkt/coffee-mode#250]
If you select the entire buffer and then press tab this shouldn't insert the tab sequence before every line, it should instead properly indent the entire buffer. Every other major mode I use works this way.

**Comment by syohex** [comment]
![coffee-indent-region](https://cloud.githubusercontent.com/assets/554281/6202293/ad8297e2-b523-11e4-89eb-4b4448cfec51.gif)

**Comment by syohex** [comment]
I have implemented this feature.
Please reopen or create new issue if you have problems or suggestions.

Thanks for suggestion.
