### ISSUE TITLE
String interpolation regression

### ISSUE THREAD

**Issue by sherrman** [defunkt/coffee-mode#289]
Maybe related to #287, 

```coffeescript
"/#{foo}/" neat
```
![screen shot 2015-02-14 at 11 18 48](https://cloud.githubusercontent.com/assets/1403628/6200773/c6d36638-b43b-11e4-9a00-424681265582.png)

Only happens when there are two forward slashes with a string interpolation block between them.  The last slash has to be the final character in the string too.

**Comment by syohex** [comment]
@sherrman Thanks for report. I have fixed at #290. Please check latest version.

Screenshot of latest version is here.

![coffee-mode](https://cloud.githubusercontent.com/assets/554281/6201950/f707c01c-b50b-11e4-991e-198291cfda8f.png)

**Comment by sherrman** [comment]
Great, thank you!
