### ISSUE TITLE
Nested string interpolations break syntax highlighting

### ISSUE THREAD

**Issue by sherrman** [defunkt/coffee-mode#292]
```coffeescript
"#{"#{seriously?}"}"
```

![screenshot 2015-02-16 20 04 10](https://cloud.githubusercontent.com/assets/1403628/6223157/fce55bf0-b616-11e4-9cb3-f54a7956f785.png)

Odd example, but... :)

**Comment by syohex** [comment]
Sorry it is impossible to highlight correctly because regular expression cannot be
used for nested structures.

**Comment by syohex** [comment]
@sherrman Please check latest version. I re-implement highlighting string interpolation.
