### ISSUE TITLE
You can install coffee-mode from MELPA with package.el?

### ISSUE THREAD

**Issue by guaka** [defunkt/coffee-mode#296]
From README.md: "You can install coffee-mode from MELPA with package.el."

http://melpa.org/#/getting-started gives me

```
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
```

But how do I get coffee-mode?

(Happy to make a pull request once I figure this out.)

**Comment by syohex** [comment]
1. `M-x package-install` 
2. Input `coffee-mode`

Like this

![install-coffee-mode](https://cloud.githubusercontent.com/assets/554281/6330488/128ecedc-bbbc-11e4-93ad-28afa9be4381.gif)

**Comment by guaka** [comment]
Great! Thanks!
