### ISSUE TITLE
closing bracket in regex breaks highlighting

### ISSUE THREAD

**Issue by sherrman** [defunkt/coffee-mode#301]
```coffee-script
noop (s) ->
  s.replace(/[]/g)
```

But all you need is `(/[]/)` and the closing parenthesis has the wrong face.

![screenshot 2015-03-03 15 56 20](https://cloud.githubusercontent.com/assets/1403628/6475344/dfc11ac0-c1bd-11e4-831a-9375b2591f3e.png)

**Comment by syohex** [comment]
I cannot reproduce as below.

![coffee-test](https://cloud.githubusercontent.com/assets/554281/6476751/4c61d0ee-c25d-11e4-847b-45c537703e4e.png)

Could you reproduce this issue only loading `coffee-mode` ?

**Comment by sherrman** [comment]
Oops, sorry about that. `rainbow-delimiters-mode` is the culprit.  Should have `describe-face`d it first.
