### ISSUE TITLE
Regexp blocks fontify strings and leak it out

### ISSUE THREAD

**Issue by sherrman** [defunkt/coffee-mode#302]
The presence of the square brackets makes single or double quotes font lock incorrectly with `font-lock-string-face` and the whole regexp block gets a default face.

```coffee
/'isok/   # OK
/Brok'n/  # Broken
```

Looks like it's broken if there is any character before the quote mark.

![screenshot 2015-03-09 10 10 05](https://cloud.githubusercontent.com/assets/1403628/6567075/2aece54a-c67f-11e4-85e4-b010ee1841d6.png)

**Comment by syohex** [comment]
Thanks for reporting.
I have fixed this issue at #303. Screenshot is here. Please check latest version.

![coffee-mode](https://cloud.githubusercontent.com/assets/554281/6568304/b63e6526-c718-11e4-88a1-6c92f9518ad1.png)

**Comment by sherrman** [comment]
:+1: awesome thank you!
