### ISSUE TITLE
Syntax highlighting broken for member variables containing underscores

### ISSUE THREAD

**Issue by kencoken** [defunkt/coffee-mode#304]
Syntax highlighting of class member variables (using the `@` operator) appears to break at the underscore character. See the below screenshot:

![screen shot 2015-03-18 at 13 56 56](https://cloud.githubusercontent.com/assets/1108445/6710157/b6c4a532-cd76-11e4-9a47-7bf13f931837.png)

In this case, for example, the `@proto_classes` member variable should be highlighted entirely in blue, but the highlighting ends at the underscore such that only `@proto` is highlighted. There are also many other examples of the same in this screenshot.

**Comment by syohex** [comment]
@kencoken Thanks for reporting. I have fixed at this issue at #305. Please check latest version.
Here is screenshot with latest version.

![coffee-mode](https://cloud.githubusercontent.com/assets/554281/6711615/6ed77e98-cdcb-11e4-8e1b-fcb9cf62550f.png)

**Comment by kencoken** [comment]
Thanks for the quick response and fix! Just checked the latest version, and seems to be working here too perfectly now! Thanks again for your work on maintaining this very-handy major mode :+1:
