### ISSUE TITLE
Add missing indenters

### ISSUE THREAD

**Issue by vladh** [defunkt/coffee-mode#307]
Indenters are currently very limited. For instance:

```coffeescript
class Test
  doThings: (done) ->
    @stuff.map (thing) ->
      console.log(thing)
  X
```

The X is where the cursor is placed when entering a new line after the `console.log` line.

**Comment by syohex** [comment]
Would you tell us what you expect ?

coffee-mode inserts same indentation as `console.log` line in such case.
Here is animation gif of such case.

![coffee](https://cloud.githubusercontent.com/assets/554281/7219697/55071296-e6e7-11e4-8176-61e0f0d82b3b.gif)

**Comment by vladh** [comment]
I'm sorry, I provided the wrong code sample. Here is the correct one:

```coffeescript
class Test
  constructor: ->
    window.runSomethiing {
      done: ->
        console.log('done')
  X   Y 
    }
```

When placing a line under `console.log`, the cursor is placed at X. I would expect it to be placed at Y.

**Comment by syohex** [comment]
Hmm, it looks expected behavior.

![coffee2](https://cloud.githubusercontent.com/assets/554281/7223069/3e30a036-e756-11e4-8c6f-bd31e11a8151.gif)

**Comment by vladh** [comment]
![Demo](http://i.imgur.com/UNb8QPV.gif)

It seems that you are right, and this is a problem with evil-mode — it only occurs when using `o`, not when using `<Return>`. I will look into it.

**Comment by vladh** [comment]
[Here's someone with the same problem.](http://stackoverflow.com/questions/18313914/how-to-remap-a-function-to-another-in-emacs) I'll probably look at their solution. Not sure if there is a way to integrate `coffee-mode` so that it works better with `evil`.

**Comment by vladh** [comment]
[Here is the solution for integrating `coffee-mode` with `evil` and `spacemacs`.](https://github.com/syl20bnr/spacemacs/blob/d56a2b0ef51abe5c5d216f6e201c4eda3d160a1e/contrib/lang/javascript/packages.el#L27) I should have just used the default `spacemacs` contrib package. Thank you regardless, @syohex.
