### ISSUE TITLE
Literal JS should be differently colored / indented / behaved

### ISSUE THREAD

**Issue by tigerhawkvok** [defunkt/coffee-mode#309]
Right now, it's just *wrongly* colored and behaves badly.

Regions fenced in by 

```coffee
# now a block of literal javascript
`
// JS Code
`
```

Should just be treated as a text string, with boring colors, rather than it breaking syntax highlighting the rest of the way down.

**Comment by syohex** [comment]
Is #310 OK ?

**Comment by tigerhawkvok** [comment]
@syohex yep

**Comment by syohex** [comment]
@tigerhawkvok I have reverted this change because someone does not want this feature.
Please add following configuration for highlighting embedded Javascript as string.

```lisp
(defun my/coffee-mode-hook ()
  (modify-syntax-entry ?` "\"" coffee-mode-syntax-table))
(add-hook 'coffee-mode-hook 'my/coffee-mode-hook)
```
