### ISSUE TITLE
Coffee-compile-region and coffee-compile-buffer not working

### ISSUE THREAD

**Issue by TheSeldonPlan** [defunkt/coffee-mode#312]
GNU emacs 24.5

From my emacs Messages buffer:
Mark set
apply: Searching for program: no such file or directory, coffee

**Comment by TheSeldonPlan** [comment]
Here is my coffeescript hook: 

(add-to-list 'auto-mode-alist '("\\.coffee\\'" . coffee-mode))
(add-to-list 'auto-mode-alist '("Cakefile" . coffee-mode))
(autoload 'coffee-mode "coffee-mode" "Major mode for editing coffeescript" t)

(defun coffee-mode-keys ()
      ;; Establishing my keybindings for coffee-mode.
     (define-key coffee-mode-map (kbd "<s-r>") 'coffee-compile-buffer)
)

(with-eval-after-load 'coffee-mode 'coffee-mode-keys)

(defun my-coffee-mode-hook ()
  ;; The following two lines of code is run from the mode hook.
  ;; These are for buffer-specific things.
  (fci-mode 1)
  (highlight-indentation-current-column-mode)
  (setq coffee-tab-width 2))
(add-hook 'coffee-mode-hook 'my-coffee-mode-hook)

**Comment by TheSeldonPlan** [comment]
You can see my full setup in my radical-emacs repo. 

Apologies if this is a known issue, google search and github issues search came up blank.

**Comment by TheSeldonPlan** [comment]
Compiling to a file works...

**Comment by syohex** [comment]
You should set environment variable PATH and `exec-path` variable.
I recommend you to use [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell).

https://github.com/purcell/exec-path-from-shell

**Comment by TheSeldonPlan** [comment]
@syohex Good call, looks like there was some weirdness in my how I set my env vars. 

+1 on the recommended package, it fixed this issue.

**Comment by sanimalp** [comment]
Only a few years late to this, but I find if I started emacs from my shell, where the coffee command dumped me into default coffee REPL, it works just fine. If, however, I start emacs from the application menu of the OS, it did not work. not currently using exec-path-from-shell, obviously..
