### ISSUE TITLE
coffee-newline-and-indent when in comment.

### ISSUE THREAD

**Issue by zw963** [defunkt/coffee-mode#325]
```coffee
# some comment <= here run coffee-newline-and-indent
```
will result in

```coffee
# some comment
# I
```

I don't know this is bug? or intentionally?

But, if I just want to add one line comment, this function is not good.
otherwize,  emacs exist add new comment command too `(indent-new-comment-line)`

**Comment by syohex** [comment]
> I don't know this is bug? or intentionally?

Intentionally.

> But, if I just want to add one line comment, this function is not good.

I think so. However coffee-mode behaves like that before I maintain. So it is difficult to change it for compatibility. Please change your configuration as below if you dislike default behavior.

```lisp
(define-key coffee-mode-map (kbd "C-m") 'nil) ;; normal new line command
(define-key coffee-mode-map (kbd "C-j") 'coffee-newline-and-indent)
```

**Comment by zw963** [comment]
Thanks.
