### ISSUE TITLE
Compile region does not produce any output

### ISSUE THREAD

**Issue by dmh43** [defunkt/coffee-mode#340]
To reproduce:

1. In a buffer type: `(my_vars) -> console.log('hello')`
2. C-x h
3. M-x coffee-compile-region

Nothing happens. The coffee compiled buffer is also empty. I expect the selected region to be compiled to JS. This seems like a simple enough fix.

**Comment by dmh43** [comment]
When I went to troubleshoot the issue, I instrumented the function `coffee-compile-region` for debugging and was able to reproduce the issue but realized that the buffer would get cleared when the function exited. I de-instrumented the function and now the command works as expected.

Will reopen the issue if I notice it happening again.

**Comment by dmh43** [comment]
I'm having this issue again. Has anyone else had the same experience with the compile region functionality?

**Comment by syohex** [comment]
Sorry too late reply. I cannot reproduce this issue.

![coffee-compile-region](https://cloud.githubusercontent.com/assets/554281/14095448/7124bcda-f59b-11e5-8665-4e8c722998ee.gif)

Could you tell us following information ?
- Emacs version
- OS
- CoffeeScript version
- Can you use `coffee` command within Emacs ? For example `M-x shell-command`, `coffee --version`
- etc

**Comment by dmh43** [comment]
CoffeeScript version: 1.10.0 (from within emacs)
GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, NS apple-appkit-1404.34) of 2016-03-02
OS X 10.11.3

Compile buffer works for me. Compile region is the only one giving me trouble. I'm also using prelude if that's relevant.

**Comment by syohex** [comment]
I have fixed at #343. Thanks for reporting issue.
