### ISSUE TITLE
How is it possible to insert new line without indenting?

### ISSUE THREAD

**Issue by kb01** [defunkt/coffee-mode#357]
Hello,

I read the doc, but I didn't find any way to insert new line without indenting below any code block I want to end -- I find it little bit boring to undo the indentation, of the line succeeding each code block end, manually - Therefore I'm asking for a solution to make the process happen more automatically.

Your help will be much appreciated.

Thank you.

**Comment by syohex** [comment]
Please overwrite key maps as below.

```
(define-key coffee-mode-map (kbd "RET") #'newline)
```

**Comment by kb01** [comment]
Thank you for the quick reply.

Adding the code to .emacs file, as you recommended above, causes the editor to ignore completely the indentation - which is not what I was expecting: Only after the last line in every code block, I need the indentation to be ignored -- so is there any possibility to achieve that?

**Comment by kb01** [comment]
Thank you for the quick reply.

Adding the code to .emacs file, as you recommended above, causes the editor to ignore completely the indentation - which is not what I was expecting: Only after the last line in every code block, I need the indentation to be ignored -- so is there any possibility to achieve that?

**Comment by syohex** [comment]
Ah, I misunderstood. There is no way. Because it is language specification and we cannot detect code block ends.

**Comment by kb01** [comment]
@syohex Ok. But, can you add a key binding that helps doing the trick at the click of a button? that would be extremely helpful.

**Comment by syohex** [comment]
No. Please add it to your configuration file by yourself.
