### ISSUE TITLE
Please upgrade version in GNU ELPA

### ISSUE THREAD

**Issue by skangas** [defunkt/coffee-mode#372]
Could you please look into upgrading the version in GNU ELPA? The version listed is 0.4.1.1.

http://elpa.gnu.org/packages/coffee-mode.html

**Comment by syohex** [comment]
I don't have GNU elpa commit permission and cannot update it. Please use [MELPA version](https://melpa.org/#/coffee-mode).

**Comment by skangas** [comment]
We would like to upgrade the version on GNU ELPA to the latest version if possible. But to do that, we need to have copyright assignment to the FSF from all significant contributors (roughly 15 lines of code). Would you be willing to sign such papers? You can read more about the reasons for this here: https://www.gnu.org/licenses/why-assign.html

If we can get the legal stuff out of the way, we could then look into how to best keep that version up to date with recent developments.

**Comment by syohex** [comment]
I have already signed. But I'm not sure other significant contributors already signed. And I suppose it is difficult(or impossible) that all contributors sign.

**Comment by monnier** [comment]
I just added it to NonGNU ELPA.

**Comment by syohex** [comment]
@monnier Thanks for your work
